### ISSUE TITLE
Cannot get card to "fit" like I want no matter what

### ISSUE THREAD

**Issue by tokenwizard** [Makin-Things/weather-radar-card#15]
I'm hopeful too much of my frustration does not come through in this post. I'm fairly new to lovelace dashboards, coming from OpenHab previously. 

I have tried Grids, Horizontal Stacks, Layout-Card, Masonry, and just about every other kind of view I can find. I have tried suggestions I've found in my searches from grid_row/grid_cols, to height: styles, etc. 

All I want is a grid that displays 3 columns and 2 rows, all cards being the same size. I will have 5 camera feeds displaying in the first five cards, then the weather radar in the sixth one. 

No matter what I try, I end up with something like this, where the radar card is twice the height of all the other cards. What am I missing. I see a log of similar questions where they response is "Check out Layout-Card" with a link to that project. I have installed it and tried it numerous ways but can't seem to get it to do what I'm after. 

Any advice for a weary guys just trying to make a symmetrical dashboard?

Thanks!

![image](https://user-images.githubusercontent.com/24832561/179608523-7971d926-a34f-447e-a9b3-e72fb2abb124.png)

If I turn on the "Render Cards as Squares" option, it just adds blank padding to each of the Picture elements to make them the same size as the long, stretched out Radar card. 

![image](https://user-images.githubusercontent.com/24832561/179608644-ed7dc4fc-cd6b-47a5-be9a-95402babdb55.png)

Also, I have tried with the "Square Map" option both on and off in the Radar card. 

Here is my card grid config:
```
square: false
columns: 3
type: grid
cards:
  - type: picture
    image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
    tap_action:
      action: none
    hold_action:
      action: none
  - type: picture
    image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
    tap_action:
      action: none
    hold_action:
      action: none
  - type: picture
    image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
    tap_action:
      action: none
    hold_action:
      action: none
  - type: picture
    image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
    tap_action:
      action: none
    hold_action:
      action: none
  - type: picture
    image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
    tap_action:
      action: none
    hold_action:
      action: none
  - type: custom:weather-radar-card
    show_recenter: true
    square_map: true
```
