### ISSUE TITLE
Feature Request: Dynamic Map Style

### ISSUE THREAD

**Issue by BrainDamage** [Makin-Things/weather-radar-card#21]
map_style allows to to toggle between light/dark map mode

It'd be nice if there's be a separate entry, called "Dynamic" ( possibly, used by default), that'd honor [Home Assistant's UI global light/dark settings](https://my.home-assistant.io/redirect/profile), so that it'd remain consistent with the rest of the application when toggling the global status

**Comment by fxxer** [comment]
I would appreciate this feature as well :)

**Comment by webmogul1** [comment]
+1 to that!

**Comment by Wuestengecko** [comment]
I got it to work with the [config-template-card](https://github.com/iantrich/config-template-card):

```yaml
type: custom:config-template-card
entities: []
variables:
  DARK_MODE: >-
    window.matchMedia && window.matchMedia('(prefers-color-scheme:
    dark)').matches
card:
  type: custom:weather-radar-card
  data_source: '${ DARK_MODE ? "RainViewer-DarkSky" : "RainViewer-Original" }'
  map_style: '${ DARK_MODE ? "Dark" : "Light" }'
```

Biggest disadvantage is, of course, that you don't have the visual editor anymore (you *have to* configure the card in YAML), so at best I'd consider this a workaround. It would still be nice to have automatic light/dark theme support natively :)
